# pubspec.yaml에 추가
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

# 아이콘 설정
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # 1024x1024 PNG 파일 경로
  
  # Android 설정
  adaptive_icon_background: "#2D6A4F"  # 녹색 배경
  adaptive_icon_foreground: "assets/icons/foreground.png"  # 전경 이미지
  
  # iOS 설정
  remove_alpha_ios: true
  
  # 웹 파비콘
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"