name: mind_attention
description: ADHD 사용자를 위한 도우미 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core (필수)
  firebase_core: ^4.0.0
  
  # Firebase Authentication
  firebase_auth: ^6.0.0
  
  # Firebase Cloud Messaging (푸시 알림)
  firebase_messaging: ^16.0.0
  
  # Firebase Analytics
  firebase_analytics: ^12.0.0
  
  # Firebase Crashlytics
  firebase_crashlytics: ^5.0.0
  
  # Firebase Performance
  firebase_performance: ^0.11.0
  
  # Firebase Remote Config
  firebase_remote_config: ^6.0.0
  
  # Google Sign In
  google_sign_in: ^6.2.1
  
  # Apple Sign In
  sign_in_with_apple: ^6.1.1
  
  # Supabase (데이터베이스)
  supabase_flutter: ^2.5.9
  
  # 상태관리
  flutter_riverpod: ^2.5.1
  
  # 로컬 알림
  flutter_local_notifications: ^17.2.2
  
  # 기타 유틸리티
  shared_preferences: ^2.2.3
  dio: ^5.5.0+1
  connectivity_plus: ^6.0.5
  easy_localization: ^3.0.7+1

  logger: ^2.0.2

  # 네비게이션
  go_router: ^10.0.0
  animated_text_kit: ^4.2.3
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# 앱 아이콘 설정
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # 1024x1024 PNG 경로
  adaptive_icon_background: "#2D6A4F"  # Android 배경색
  remove_alpha_ios: true  # iOS 투명도 제거

flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
    - assets/images/onboarding/
