name: mind_attention
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase 관련 패키지
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_analytics: ^11.3.4
  firebase_messaging: ^15.1.4
  firebase_storage: ^12.3.5
  firebase_crashlytics: ^4.1.4

  # Supabase 관련 패키지
  supabase_flutter: ^2.8.1

  # 상태관리
  provider: ^6.1.2
  
  # 라우팅
  go_router: ^14.6.2

  # 로컬 알림
  flutter_local_notifications: ^18.0.1
  
  # 타이머/스톱워치
  stop_watch_timer: ^3.2.1
  
  # 차트 및 데이터 시각화
  fl_chart: ^0.70.0
  
  # 로컬 저장소
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # 날짜/시간 처리
  intl: ^0.19.0
  
  # UI/UX 개선
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  
  # 유틸리티
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1
  
  # 앱 개선 및 피드백
  flutter_rating_bar: ^4.0.1
  in_app_review: ^2.0.10
  
  # 게임화 요소
  confetti: ^0.7.0
  
  # 오디오 (집중력 향상 사운드)
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Hive 코드 생성
  build_runner: ^2.4.13
  hive_generator: ^2.0.1


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
#    - assets/images/
#    - assets/animations/
#    - assets/sounds/
#    - assets/icons/

